//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.02 at 05:24:47 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.topografix.com/GPX/1/1")
package ch.shimbawa.jorofi.xml;
